# Changes here will be overwritten by Copier
_commit: v0.3.0
_src_path: gl:climate-resource/copier-core-python-repository
email: zebedee.nicholls@climate-energy-college.org
initial_setup: true
name: Zebedee Nicholls
notebook_dependencies: false
pandas_doctests: false
plot_dependencies: false
project_description_short: Handling of units related to simple climate modelling.
project_name_human: OpenSCM-Units
project_name_pip: openscm-units
project_name_python: openscm_units
project_url: https://github.com/openscm/openscm-units
